name: mini_dating_app_prototype
description: "mini_dating_app_prototype"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Utility Packages
  http: ^1.6.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  permission_handler: ^12.0.0+1
  vibration: ^3.1.3
  flutter_dotenv: ^6.0.0
  local_auth: ^2.3.0
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.3.1
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  flutter_secure_storage: ^9.2.4

  # Icons Packages
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #Maps Integration
  mapbox_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3

  #Firebase
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/dating-app-icon-logo.png"
  adaptive_icon_foreground: "assets/logos/dating-app-icon-logo.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  # Local assets
  assets:
    - .env
    - assets/logos/
    - assets/icons/
    - assets/images/email_verification/
    - assets/images/password_reset/
    - assets/images/loading/
    - assets/images/payments/
    - assets/images/signin/
    - assets/images/default_avatar/
    - assets/images/status/
    - assets/images/map/

  # Local fonts:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
        - asset: assets/fonts/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 800